x-postgres-common:
  &x-postgres-common
  image: bitnami/postgresql
  restart: always
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    interval: 1m30s
    timeout: 30s
    retries: 5
    start_period: 30s

services:
  master:
    <<: *x-postgres-common
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator
      - POSTGRESQL_USERNAME=${POSTGRES_USER?Variable not set}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRESQL_DATABASE=${POSTGRES_DB?Variable not set}
      - ALLOW_EMPTY_PASSWORD=yes

  slave:
    <<: *x-postgres-common
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      master:
        condition: service_healthy
